#!/bin/ksh 
OUTPUT=gnupl.jpg

cat >gnupl.cmd <<EOD
set term jpeg size 1200,800
set output "$OUTPUT"
set logscale x
set xrange [1:]
EOD


PLOT='plot'
COMMA=''
X=0
for F in $*
do
  X=$(($X+1))
  printf "%s"  "$PLOT $COMMA '$F' using 1:5 w lines lt $X lc $X lw 3" 
  PLOT=''
  COMMA=', '
done >>gnupl.cmd


gnuplot -persist gnupl.cmd

display $OUTPUT 

